"""Add notes to Case

Revision ID: f7a70820b061
Revises: 67989b0ae36f
Create Date: 2026-04-01 20:39:09.514100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7a70820b061'
down_revision: Union[str, None] = '67989b0ae36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('cases', 'flow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('prescription_tokens', 'qr_storage_key')
    op.alter_column('symptom_flows', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symptom_flows', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('prescription_tokens', sa.Column('qr_storage_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('cases', 'flow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cases', 'notes')
    # ### end Alembic commands ###
